name: Build & Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Run `yarn install`
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Setup npm auth
        run: yarn config set 'npmScopes["voxject"].npmAuthToken' ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: yarn npm publish

      - name: Add tag
        uses: neverendingqs/gh-action-tag-on-npm-version@master
